kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3-default
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
  iops: "3000"
  throughput: "125"
mountOptions:
  - nodelalloc
  - noatime