kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3-tiflash
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
  iops: "6000"
  throughput: "600"
mountOptions:
  - nodelalloc
  - noatime