systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongos.log

processManagement:
  fork: true
  pidFilePath: /var/run/mongodb/mongos.pid

net:
  port: 27017
  bindIp: 0.0.0.0

sharding:
  configDB: configRS/N1:27019,N2:27019,N3:27019