systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/configsvr.log

storage:
  dbPath: /data/configdb

processManagement:
  fork: true
  pidFilePath: /var/run/mongodb/configsvr.pid

net:
  port: 27019
  bindIp: 0.0.0.0

replication:
  replSetName: configRS

sharding:
  clusterRole: configsvr