systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/shard2.log

storage:
  dbPath: /data/shard2
  wiredTiger:
    engineConfig:
      cacheSizeGB: 20

processManagement:
  fork: true
  pidFilePath: /var/run/mongodb/shard2.pid

net:
  port: 27020
  bindIp: 0.0.0.0

replication:
  replSetName: shard2RS

sharding:
  clusterRole: shardsvr