systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/shard1.log

storage:
  dbPath: /data/shard1
  wiredTiger:
    engineConfig:
      cacheSizeGB: 20

processManagement:
  fork: true
  pidFilePath: /var/run/mongodb/shard1.pid

net:
  port: 27018
  bindIp: 0.0.0.0

replication:
  replSetName: shard1RS

sharding:
  clusterRole: shardsvr